/*Queries that provide answers to the questions from all projects.*/

SELECT * from animals WHERE name like '%mon';
SELECT name FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-12-31';
SELECT name FROM animals WHERE neutered = 'true' AND escape_attempts < 3;
SELECT date_of_birth FROM animals WHERE name in ('Agumon','Pikachu');
SELECT name, escape_attempts FROM animals WHERE weight_kg > 10.5;
SELECT * FROM animals WHERE neutered = 'true';
SELECT * FROM animals WHERE name <> 'Gabumon';
SELECT * FROM animals WHERE weight_kg BETWEEN  10.4 AND 17.3;

BEGIN;
ALTER TABLE animals RENAME COLUMN SPECIES TO UNSPECIFIED;
SELECT * FROM ANIMALS;
ROLLBACK;
SELECT * FROM ANIMALS;

BEGIN;
UPDATE ANIMALS SET SPECIES = 'digimon' WHERE name LIKE '%mon';
UPDATE ANIMALS SET SPECIES = 'pokemon' WHERE SPECIES IS NULL;
COMMIT;
SELECT * FROM ANIMALS;

BEGIN;
DELETE FROM ANIMALS;
SELECT * FROM ANIMALS;
ROLLBACK;
SELECT * FROM ANIMALS;

BEGIN;
DELETE FROM ANIMALS WHERE date_of_birth > '2022-01-01';
SAVEPOINT SAVEPOIN_1;
UPDATE ANIMALS SET weight_kg = weight_kg * -1;
ROLLBACK TO SAVEPOIN_1;
UPDATE ANIMALS SET weight_kg = weight_kg * -1 WHERE weight_kg < 0;
COMMIT;
SELECT * FROM ANIMALS;

SELECT COUNT(*) AS TOTAL_ANIMALS FROM ANIMALS;
SELECT COUNT (*) AS NEVER_ESCAPE FROM ANIMALS WHERE ESCAPE_ATTEMPTS = 0;
SELECT AVG(WEIGHT_KG) AS AVA_WEIGHT_KG FROM ANIMALS;
SELECT neutered, SUM(ESCAPE_ATTEMPTS) AS TOTAL_ESCAP_ATM FROM ANIMALS GROUP BY neutered;
SELECT SPECIES, MIN(WEIGHT_KG) AS MIN_WEIGHT_KG, MAX(WEIGHT_KG) AS MAX_WEIGHT_KG FROM ANIMALS GROUP BY SPECIES;
SELECT SPECIES, AVG(ESCAPE_ATTEMPTS) as AVG_ESCATM FROM ANIMALS WHERE date_of_birth BETWEEN '1990-01-01' AND '2000-12-31' GROUP BY SPECIES;
