/*Queries that provide answers to the questions from all projects.*/

SELECT * from animals WHERE name like '%mon';
SELECT name FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-12-31';
SELECT name FROM animals WHERE neutered = 'true' AND escape_attempts < 3;
SELECT date_of_birth FROM animals WHERE name in ('Agumon','Pikachu');
SELECT name, escape_attempts FROM animals WHERE weight_kg > 10.5;
SELECT * FROM animals WHERE neutered = 'true';
SELECT * FROM animals WHERE name <> 'Gabumon';
SELECT * FROM animals WHERE weight_kg BETWEEN  10.4 AND 17.3;

BEGIN;
ALTER TABLE animals RENAME COLUMN SPECIES TO UNSPECIFIED;
SELECT * FROM ANIMALS;
ROLLBACK;
SELECT * FROM ANIMALS;

BEGIN;
UPDATE ANIMALS SET SPECIES = 'digimon' WHERE name LIKE '%mon';
UPDATE ANIMALS SET SPECIES = 'pokemon' WHERE SPECIES IS NULL;
COMMIT;
SELECT * FROM ANIMALS;

BEGIN;
DELETE FROM ANIMALS;
SELECT * FROM ANIMALS;
ROLLBACK;
SELECT * FROM ANIMALS;

BEGIN;
DELETE FROM ANIMALS WHERE date_of_birth > '2022-01-01';
SAVEPOINT SAVEPOIN_1;
UPDATE ANIMALS SET weight_kg = weight_kg * -1;
ROLLBACK TO SAVEPOIN_1;
UPDATE ANIMALS SET weight_kg = weight_kg * -1 WHERE weight_kg < 0;
COMMIT;
SELECT * FROM ANIMALS;

SELECT COUNT(*) AS TOTAL_ANIMALS FROM ANIMALS;
SELECT COUNT (*) AS NEVER_ESCAPE FROM ANIMALS WHERE ESCAPE_ATTEMPTS = 0;
SELECT AVG(WEIGHT_KG) AS AVA_WEIGHT_KG FROM ANIMALS;
SELECT neutered, SUM(ESCAPE_ATTEMPTS) AS TOTAL_ESCAP_ATM FROM ANIMALS GROUP BY neutered;
SELECT SPECIES, MIN(WEIGHT_KG) AS MIN_WEIGHT_KG, MAX(WEIGHT_KG) AS MAX_WEIGHT_KG FROM ANIMALS GROUP BY SPECIES;
SELECT SPECIES, AVG(ESCAPE_ATTEMPTS) as AVG_ESCATM FROM ANIMALS WHERE date_of_birth BETWEEN '1990-01-01' AND '2000-12-31' GROUP BY SPECIES;

SELECT NAME, FULL_NAME
FROM ANIMALS
JOIN OWNERS ON ANIMALS.OWNER_ID = OWNERS.ID
WHERE FULL_NAME = 'Melody Pond';

SELECT * FROM ANIMALS
JOIN SPECIES ON SPECIES.ID = ANIMALS.SPECIES_ID
WHERE SPECIES.NAME = 'Pokemon';

SELECT OWNERS.FULL_NAME, ANIMALS.NAME
FROM OWNERS
LEFT JOIN ANIMALS ON ANIMALS.OWNER_ID = OWNERS.ID;

SELECT  SPECIES.NAME, COUNT(ANIMALS.NAME) AS TOTAL
FROM ANIMALS
JOIN SPECIES ON ANIMALS.SPECIES_ID = SPECIES.ID
GROUP BY SPECIES.NAME;

SELECT SPECIES.NAME,
OWNERS.FULL_NAME,
ANIMALS.NAME
FROM SPECIES
JOIN ANIMALS ON ANIMALS.SPECIES_ID = SPECIES.ID
JOIN OWNERS ON ANIMALS.OWNER_ID = OWNERS.ID
WHERE SPECIES.NAME = 'Digimon'
AND OWNERS.FULL_NAME = 'Jennifer Orwell';

SELECT ANIMALS.NAME AS ANIMALS_NAME,
OWNERS.FULL_NAME
FROM ANIMALS
JOIN OWNERS ON ANIMALS.OWNER_ID = OWNERS.ID
WHERE OWNERS.FULL_NAME = 'Dean Winchester' AND ANIMALS.ESCAPE_ATTEMPTS = 0;

SELECT OWNERS.FULL_NAME, COUNT(*) AS MOST_ANIMALS
FROM ANIMALS
JOIN OWNERS ON ANIMALS.OWNER_ID = OWNERS.ID
GROUP BY FULL_NAME ORDER BY COUNT(*) DESC LIMIT 1;


SELECT ANIMALS.NAME AS ANIMAL_NAME, VETS.NAME AS VET_NAME, VISITS.VISIT_DATE
FROM ANIMALS, VETS, VISITS WHERE VETS.NAME = 'William Tatcher'
AND VETS.ID = VISITS.VETS_ID
AND ANIMALS.ID = VISITS.ANIMALS_ID ORDER BY VISIT_DATE DESC LIMIT 1;